apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrate
spec:
  template:
    metadata:
      name: database-migrate
    spec:
      containers:
      - name: database-migrate
        image: operationaldev/test-ops:stable
        command: ["/usr/local/bundle/bin/rake"]
        args: ["db:migrate"] # RAILS_ENV=development"]
        env:
        - name: DATABASE_NAME
          value: "gorgeous-code_test"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgres"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: "db-user"
              key: "username"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "db-user-pass"
              key: "password"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
      restartPolicy: Never
