apiVersion: v1
kind: ReplicationController
metadata:
  name: rails
spec:
  replicas: 1
  selector:
    app: rails-kube-app
    tier: rails
  template:
    metadata:
      name: rails
      labels:
        app: rails-kube-app
        tier: rails
    spec:
      containers:
      - name: rails
        image: operationaldev/test-ops:stable
        env:
        - name: DATABASE_NAME
          value: "gorgeous-code_test"
        - name: DATABASE_URL
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: "db-user"
              key: "username"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "db-user-pass"
              key: "password"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
        ports:
        - containerPort: 3000
