default: &default
  adapter: postgresql
  endcoding: utf8
  pool: 5
  timeout: 5000
  host: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: gorgeous-code_development

test:
  <<: *default
  database: gorgeous-code_test

production:
  <<: *default
  database: gorgeous-code_production
